### ISSUE TITLE
Support for tags/dimensions

### ISSUE THREAD

**Issue by gomete** [justeattakeaway/JustEat.StatsD#268]
Hi all!

It would be amazing to allow tags. AFAIK, it is not part of the specification but it is supported by some of the major providers:

- https://docs.datadoghq.com/getting_started/tagging/
- https://www.datadoghq.com/blog/the-power-of-tagged-metrics/
- https://docs.splunk.com/Documentation/Splunk/8.0.5/Metrics/GetMetricsInStatsd
- https://docs.signalfx.com/en/latest/integrations/agent/monitors/collectd-statsd.html#adding-dimensions-to-statsd-metrics
- https://www.influxdata.com/blog/getting-started-with-sending-statsd-metrics-to-telegraf-influxdb/#introducing-influx-statsd
- https://github.com/librato/statsd-librato-backend#tags

There are [several flavours to add tags based on the provider](https://github.com/prometheus/statsd_exporter).

There is already [a pull request that covers tagging](https://github.com/justeat/JustEat.StatsD/pull/229) but it does not support at least the 4 flavours depicted above.

**Comment by martincostello** [comment]
Sorry for the incredibly long delay - tagging is now supported in JustEat.StatsD 5.0.0 which was just published to NuGet.org.
