### ISSUE TITLE
Documentation for Timing feature is incorrect

### ISSUE THREAD

**Issue by mtn-boblloyd** [justeattakeaway/JustEat.StatsD#599]
### Expected behaviour

In the `Example of using the interface` section, in the code block, we see this:
```
stats.Timing(statName, stopWatch.Elapsed);
```
However, the interface for the Timing method is:
```
stats.Timing(stopWatch.Elapsed, rate, statName);
```
As per the code:
https://github.com/justeattakeaway/JustEat.StatsD/blob/3623a67a65659ef05eb8b8e7d583f9e209060d9b/src/JustEat.StatsD/IStatsDPublisher.cs#L29

### Actual behaviour

_Explain what actually happened. If an exception occurred, please include a stack trace if available._

### Steps to reproduce

_A concise, repeatable, example of how to illustrate the issue._

**Comment by martincostello** [comment]
Thanks for pointing this out - it's probably been broken for a long time since major refactoring one or more amjor releases ago. Would you like to submit a PR to update the example?
