### ISSUE TITLE
IStatsDPublisherWithTags missing IoC registration

### ISSUE THREAD

**Issue by BigDaddy1337** [justeattakeaway/JustEat.StatsD#661]
Explain please how to use IStatsDPublisherWithTags, [there](https://github.com/justeattakeaway/JustEat.StatsD/blob/v5.0.0/src/JustEat.StatsD/StatsDServiceCollectionExtensions.cs) is no registration of this interface. I need to send metrics with tags, but the documentation doesn't explain how to use IStatsDPublisherWithTags

**Comment by martincostello** [comment]
Thanks for reporting this issue - the missing IoC registration is a bug. See #662.

**Comment by BigDaddy1337** [comment]
@martincostello thank for the quick response and investigation! 🎉  I'll wait for the fix release

**Comment by martincostello** [comment]
Thanks again - the fix is now available in [v5.0.1](https://www.nuget.org/packages/JustEat.StatsD/5.0.1).
